name: Markdown link check

on:
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/markdown-link-check-config.json
    - name: Inform Slack users of link check failures
      uses: tiloio/slack-webhook-action@v1.1.2
      if: ${{ failure() && steps.extract_branch.outputs.branch == 'main' }}
      with: 
        slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_BRIMLABS_DOCS }}
        slack_json: |
          {
            "username": "markdown-link-check",
            "text": "Markdown link check failed: https://github.com/{{GITHUB_REPOSITORY}}/actions/runs/{{GITHUB_RUN_ID}}"
          }
